name: Build All Projects

on:
  workflow_dispatch:
  push:
    paths: # Collected from paths of all jobs below
    - 'include/**'
    - 'lib/**'
    - 'ug_example/**'
    
env:
  BUILD_TYPE: Release
  TOOLS_SUB_DIR: 'ug_example/tools'
  BUILD_PATH: '../build/bfRU'

jobs:

  Check-Build-user_guide_example:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      ok_to_proceed: ${{ steps.check.outputs.ok_to_proceed_val }}
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Get changed files in concerned folder(s)
      id: changed-files-specific
      uses: tj-actions/changed-files@v35
      with:
        files: |
          lib/**
          include/**
          ug_example/**
          .github/workflows/build_all.yml
          
    # Check if any file(s) in the concerned folder changed
    - name: Check
      id: check
      if: steps.changed-files-specific.outputs.any_changed == 'false'
      run: |
        echo "No concerned files changed, suppressing processing."       
        echo "ok_to_proceed_val=N" >> $GITHUB_OUTPUT
        
  Build-Ubuntu:
    needs: Check-Build-user_guide_example
    runs-on: ubuntu-latest

    steps:
    - name: echo Suppress Status if Needed
      if: ${{needs.Check-Build-user_guide_example.outputs.ok_to_proceed == 'N' }}
      run: |
        echo "Job execution processing is suppressed for no cencerned files are changed."
        
    - name: Checkout Code
      if: ${{needs.Check-Build-user_guide_example.outputs.ok_to_proceed != 'N' }}
      uses: actions/checkout@v3

    - name: Configure CMake and Build
      if: ${{needs.Check-Build-user_guide_example.outputs.ok_to_proceed != 'N' }}
      run: |
        cd ${{env.TOOLS_SUB_DIR}}
        cmake -B ${{env.BUILD_PATH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{env.BUILD_PATH}}
        
    - name: Archive output
      uses: actions/upload-artifact@v3
      with:
          name: Ubuntu-ug_ex
          path: lib/x64/ndigo_ugex
        
  Build-Win:
    needs: Check-Build-user_guide_example
    runs-on:  windows-latest

    steps:
    - name: echo Suppress Status if Needed
      if: ${{needs.Check-Build-user_guide_example.outputs.ok_to_proceed == 'N' }}
      run: |
        echo "Job execution processing is suppressed for no cencerned files are changed."
        
    - name: Checkout Code
      if: ${{needs.Check-Build-user_guide_example.outputs.ok_to_proceed != 'N' }}
      uses: actions/checkout@v3

    - name: Configure CMake and Build
      if: ${{needs.Check-Build-user_guide_example.outputs.ok_to_proceed != 'N' }}
      run: |
        cd ${{env.TOOLS_SUB_DIR}}
        cmake -B ${{env.BUILD_PATH}}
        cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}}
        
    - name: Archive output
      uses: actions/upload-artifact@v3
      with:
          name: Ubuntu-ug_ex
          path: lib/x64/Release/ndigo_ugex.exe
